beolink_join:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    beolink_jid:
      required: false
      example: 1111.2222222.33333333@products.bang-olufsen.com
      selector:
        text:

beolink_expand:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    beolink_jids:
      required: true
      example: >-
        [
          1111.2222222.33333333@products.bang-olufsen.com,
          4444.5555555.66666666@products.bang-olufsen.com
        ]
      selector:
        object:

beolink_unexpand:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    beolink_jids:
      required: true
      example: >-
        [
          1111.2222222.33333333@products.bang-olufsen.com,
          4444.5555555.66666666@products.bang-olufsen.com
        ]
      selector:
        object:

beolink_leave:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen

beolink_allstandby:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen

beolink_set_volume:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    volume_level:
      required: true
      example: 0.4
      selector:
        text:

beolink_set_relative_volume:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    volume_level:
      required: true
      example: 0.2
      selector:
        text:

beolink_leader_command:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    command:
      required: true
      example: "set_volume_level"
      selector:
        select:
          options:
            - "media_next_track"
            - "media_pause"
            - "media_play_pause"
            - "media_play"
            - "media_previous_track"
            - "media_seek"
            - "media_stop"
            - "mute_volume"
            - "select_source"
            - "set_relative_volume_level"
            - "set_volume_level"
            - "toggle"
            - "volume_down"
            - "volume_up"
    parameter:
      required: false
      example: 0.4
      selector:
        text:

overlay_audio:
  target:
    entity:
      integration: bangolufsen
      domain: media_player
    device:
      integration: bangolufsen
  fields:
    uri:
      required: false
      selector:
        text:
    absolute_volume:
      required: false
      example: 40
      selector:
        number:
          min: 0
          max: 100
    volume_offset:
      required: false
      example: 10
      selector:
        number:
          min: 0
          max: 100
    tts:
      required: false
      example: This is a test
      selector:
        text:
    tts_language:
      required: false
      example: en-us
      selector:
        text:
